from __future__ import annotations

import re
import sqlite3
from datetime import datetime, timezone
from typing import Any, Iterable

from .config import DATA_DIR, DATABASE_URL, DB_PATH, UPLOADS_DIR
from .parashot import DEFAULT_PARASHOT

IS_POSTGRES = bool(DATABASE_URL)
DEFAULT_STATUS = "פורסם"


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat(timespec="seconds")


class Database:
    def __init__(self) -> None:
        if IS_POSTGRES:
            import psycopg
            from psycopg.rows import dict_row

            self.conn = psycopg.connect(
                DATABASE_URL,
                row_factory=dict_row,
                prepare_threshold=None,
            )
        else:
            DATA_DIR.mkdir(parents=True, exist_ok=True)
            UPLOADS_DIR.mkdir(parents=True, exist_ok=True)
            self.conn = sqlite3.connect(DB_PATH)
            self.conn.row_factory = sqlite3.Row
            self.conn.execute("PRAGMA foreign_keys = ON")

    def __enter__(self) -> "Database":
        return self

    def __exit__(self, exc_type, exc, tb) -> None:
        if exc_type:
            self.conn.rollback()
        else:
            self.conn.commit()
        self.conn.close()

    def execute(self, sql: str, params: Iterable[Any] = ()):
        return self.conn.execute(sql_for_backend(sql), tuple(params))

    def executemany(self, sql: str, params: Iterable[Iterable[Any]]):
        if IS_POSTGRES:
            cursor = self.conn.cursor()
            cursor.executemany(sql_for_backend(sql), params)
            return cursor
        return self.conn.executemany(sql_for_backend(sql), params)

    def executescript(self, sql: str) -> None:
        if IS_POSTGRES:
            self.conn.execute(sql)
        else:
            self.conn.executescript(sql)


def sql_for_backend(sql: str) -> str:
    if not IS_POSTGRES:
        return sql
    return sql.replace("?", "%s")


def connect() -> Database:
    return Database()


def schema_sql() -> str:
    id_type = (
        "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        if IS_POSTGRES
        else "INTEGER PRIMARY KEY AUTOINCREMENT"
    )
    return f"""
        CREATE TABLE IF NOT EXISTS parashot (
            id {id_type},
            name TEXT NOT NULL UNIQUE,
            created_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS tags (
            id {id_type},
            name TEXT NOT NULL UNIQUE,
            created_at TEXT NOT NULL
        );

        CREATE TABLE IF NOT EXISTS articles (
            id {id_type},
            title TEXT NOT NULL,
            subtitle TEXT,
            issue_number TEXT,
            parasha_id INTEGER NOT NULL REFERENCES parashot(id),
            author_name TEXT,
            publication_date TEXT,
            uploaded_at TEXT NOT NULL,
            body_text TEXT,
            extracted_text TEXT,
            status TEXT NOT NULL DEFAULT '{DEFAULT_STATUS}',
            original_filename TEXT,
            stored_filename TEXT,
            file_path TEXT,
            file_type TEXT,
            image_original_filename TEXT,
            image_stored_filename TEXT,
            image_path TEXT,
            image_type TEXT
        );

        CREATE TABLE IF NOT EXISTS article_tags (
            article_id INTEGER NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
            tag_id INTEGER NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
            PRIMARY KEY (article_id, tag_id)
        );

        CREATE INDEX IF NOT EXISTS idx_articles_parasha_id ON articles(parasha_id);
        CREATE INDEX IF NOT EXISTS idx_articles_publication_date ON articles(publication_date);
        CREATE INDEX IF NOT EXISTS idx_articles_uploaded_at ON articles(uploaded_at);
        CREATE INDEX IF NOT EXISTS idx_article_tags_tag_id ON article_tags(tag_id);
    """


def init_db() -> None:
    with connect() as conn:
        conn.executescript(schema_sql())
        ensure_article_columns(conn)
        now = utc_now()
        if IS_POSTGRES:
            conn.executemany(
                "INSERT INTO parashot (name, created_at) VALUES (?, ?) ON CONFLICT (name) DO NOTHING",
                [(name, now) for name in DEFAULT_PARASHOT],
            )
        else:
            conn.executemany(
                "INSERT OR IGNORE INTO parashot (name, created_at) VALUES (?, ?)",
                [(name, now) for name in DEFAULT_PARASHOT],
            )
        conn.executemany(
            "UPDATE parashot SET name = ? WHERE id = ?",
            [(name, index + 1) for index, name in enumerate(DEFAULT_PARASHOT)],
        )


def ensure_article_columns(conn: Database) -> None:
    if IS_POSTGRES:
        rows = conn.execute(
            """
            SELECT column_name AS name
            FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = 'articles'
            """
        ).fetchall()
    else:
        rows = conn.execute("PRAGMA table_info(articles)").fetchall()
    columns = {row["name"] for row in rows}
    migrations = {
        "subtitle": "ALTER TABLE articles ADD COLUMN subtitle TEXT",
        "issue_number": "ALTER TABLE articles ADD COLUMN issue_number TEXT",
        "image_original_filename": "ALTER TABLE articles ADD COLUMN image_original_filename TEXT",
        "image_stored_filename": "ALTER TABLE articles ADD COLUMN image_stored_filename TEXT",
        "image_path": "ALTER TABLE articles ADD COLUMN image_path TEXT",
        "image_type": "ALTER TABLE articles ADD COLUMN image_type TEXT",
    }
    for column, statement in migrations.items():
        if column not in columns:
            conn.execute(statement)


def row_to_dict(row: sqlite3.Row | dict[str, Any]) -> dict[str, Any]:
    return dict(row)


def normalize_tag_names(raw: str | None) -> list[str]:
    if not raw:
        return []
    names = [part.strip() for part in re.split(r"[,;\n]+", raw) if part.strip()]
    unique: list[str] = []
    seen: set[str] = set()
    for name in names:
        key = name.casefold()
        if key not in seen:
            seen.add(key)
            unique.append(name)
    return unique


def get_or_create_tags(conn: Database, names: list[str]) -> list[int]:
    ids: list[int] = []
    now = utc_now()
    for name in names:
        if IS_POSTGRES:
            conn.execute(
                "INSERT INTO tags (name, created_at) VALUES (?, ?) ON CONFLICT (name) DO NOTHING",
                (name, now),
            )
        else:
            conn.execute(
                "INSERT OR IGNORE INTO tags (name, created_at) VALUES (?, ?)",
                (name, now),
            )
        row = conn.execute("SELECT id FROM tags WHERE name = ?", (name,)).fetchone()
        if row:
            ids.append(int(row["id"]))
    return ids


def attach_tags(conn: Database, article_id: int, tag_ids: list[int]) -> None:
    conn.executemany(
        "INSERT INTO article_tags (article_id, tag_id) VALUES (?, ?) ON CONFLICT DO NOTHING"
        if IS_POSTGRES
        else "INSERT OR IGNORE INTO article_tags (article_id, tag_id) VALUES (?, ?)",
        [(article_id, tag_id) for tag_id in tag_ids],
    )


def load_article_tags(conn: Database, article_id: int) -> list[dict[str, Any]]:
    rows = conn.execute(
        """
        SELECT tags.id, tags.name
        FROM tags
        JOIN article_tags ON article_tags.tag_id = tags.id
        WHERE article_tags.article_id = ?
        ORDER BY tags.name
        """,
        (article_id,),
    ).fetchall()
    return [row_to_dict(row) for row in rows]


def load_tags_for_articles(conn: Database, article_ids: list[int]) -> dict[int, list[dict[str, Any]]]:
    if not article_ids:
        return {}

    placeholders = ",".join("?" for _ in article_ids)
    rows = conn.execute(
        f"""
        SELECT article_tags.article_id, tags.id, tags.name
        FROM article_tags
        JOIN tags ON article_tags.tag_id = tags.id
        WHERE article_tags.article_id IN ({placeholders})
        ORDER BY tags.name
        """,
        article_ids,
    ).fetchall()

    tags_by_article: dict[int, list[dict[str, Any]]] = {article_id: [] for article_id in article_ids}
    for row in rows:
        item = row_to_dict(row)
        article_id = int(item.pop("article_id"))
        tags_by_article.setdefault(article_id, []).append(item)
    return tags_by_article


def article_from_row(conn: Database, row: sqlite3.Row | dict[str, Any]) -> dict[str, Any]:
    article = row_to_dict(row)
    article["tags"] = load_article_tags(conn, int(article["id"]))
    return article


def articles_from_rows(conn: Database, rows: Iterable[sqlite3.Row | dict[str, Any]]) -> list[dict[str, Any]]:
    articles = [row_to_dict(row) for row in rows]
    tags_by_article = load_tags_for_articles(conn, [int(article["id"]) for article in articles])
    for article in articles:
        article["tags"] = tags_by_article.get(int(article["id"]), [])
    return articles


def insert_returning_id(conn: Database, sql: str, params: Iterable[Any]) -> int:
    if IS_POSTGRES:
        row = conn.execute(f"{sql} RETURNING id", params).fetchone()
        return int(row["id"])
    cursor = conn.execute(sql, params)
    return int(cursor.lastrowid)
