-- Initial Supabase/Postgres schema for the Aloney Shabbat article system.
-- Safe to run more than once in the Supabase SQL Editor.

CREATE TABLE IF NOT EXISTS public.parashot (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.tags (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS public.articles (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    subtitle TEXT,
    issue_number TEXT,
    parasha_id INTEGER NOT NULL REFERENCES public.parashot(id),
    author_name TEXT,
    publication_date TEXT,
    uploaded_at TEXT NOT NULL,
    body_text TEXT,
    extracted_text TEXT,
    status TEXT NOT NULL DEFAULT 'פורסם',
    original_filename TEXT,
    stored_filename TEXT,
    file_path TEXT,
    file_type TEXT,
    image_original_filename TEXT,
    image_stored_filename TEXT,
    image_path TEXT,
    image_type TEXT
);

CREATE TABLE IF NOT EXISTS public.article_tags (
    article_id INTEGER NOT NULL REFERENCES public.articles(id) ON DELETE CASCADE,
    tag_id INTEGER NOT NULL REFERENCES public.tags(id) ON DELETE CASCADE,
    PRIMARY KEY (article_id, tag_id)
);

CREATE INDEX IF NOT EXISTS idx_articles_parasha_id ON public.articles(parasha_id);
CREATE INDEX IF NOT EXISTS idx_articles_publication_date ON public.articles(publication_date);
CREATE INDEX IF NOT EXISTS idx_articles_uploaded_at ON public.articles(uploaded_at);
CREATE INDEX IF NOT EXISTS idx_article_tags_tag_id ON public.article_tags(tag_id);

INSERT INTO public.parashot (id, name, created_at) VALUES
    (1, 'בראשית', now()::text),
    (2, 'נח', now()::text),
    (3, 'לך לך', now()::text),
    (4, 'וירא', now()::text),
    (5, 'חיי שרה', now()::text),
    (6, 'תולדות', now()::text),
    (7, 'ויצא', now()::text),
    (8, 'וישלח', now()::text),
    (9, 'וישב', now()::text),
    (10, 'מקץ', now()::text),
    (11, 'ויגש', now()::text),
    (12, 'ויחי', now()::text),
    (13, 'שמות', now()::text),
    (14, 'וארא', now()::text),
    (15, 'בא', now()::text),
    (16, 'בשלח', now()::text),
    (17, 'יתרו', now()::text),
    (18, 'משפטים', now()::text),
    (19, 'תרומה', now()::text),
    (20, 'תצוה', now()::text),
    (21, 'כי תשא', now()::text),
    (22, 'ויקהל', now()::text),
    (23, 'פקודי', now()::text),
    (24, 'ויקרא', now()::text),
    (25, 'צו', now()::text),
    (26, 'שמיני', now()::text),
    (27, 'תזריע', now()::text),
    (28, 'מצורע', now()::text),
    (29, 'אחרי מות', now()::text),
    (30, 'קדושים', now()::text),
    (31, 'אמור', now()::text),
    (32, 'בהר', now()::text),
    (33, 'בחוקותי', now()::text),
    (34, 'במדבר', now()::text),
    (35, 'נשא', now()::text),
    (36, 'בהעלותך', now()::text),
    (37, 'שלח', now()::text),
    (38, 'קרח', now()::text),
    (39, 'חקת', now()::text),
    (40, 'בלק', now()::text),
    (41, 'פינחס', now()::text),
    (42, 'מטות', now()::text),
    (43, 'מסעי', now()::text),
    (44, 'דברים', now()::text),
    (45, 'ואתחנן', now()::text),
    (46, 'עקב', now()::text),
    (47, 'ראה', now()::text),
    (48, 'שופטים', now()::text),
    (49, 'כי תצא', now()::text),
    (50, 'כי תבוא', now()::text),
    (51, 'נצבים', now()::text),
    (52, 'וילך', now()::text),
    (53, 'האזינו', now()::text),
    (54, 'וזאת הברכה', now()::text)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name;

SELECT setval(
    pg_get_serial_sequence('public.parashot', 'id'),
    GREATEST((SELECT COALESCE(MAX(id), 1) FROM public.parashot), 1),
    true
);
